import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FileManagerProvider } from "@/store";
import "react-toastify/dist/ReactToastify.css";
import ToastContainerNOSSR from "@/components/toast-container";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FileManagerProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <nav className="px-6 py-2">
            <h1>Multi Uploader</h1>
          </nav>
          {children}
          <ToastContainerNOSSR />
        </body>
      </FileManagerProvider>
    </html>
  );
}
